name: CI

on: [push]

jobs:
  test:
    name: Test on node 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Run
        run: |
          yarn --frozen-lockfile
          yarn lint
          yarn typecheck
          yarn test

  build:
    name: Build on node 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build
        run: |
          yarn --frozen-lockfile
          yarn build
